[versions]
kotlin = "1.9.20"
compose = "1.5.10"
coroutines = "1.7.3"
maven-publish = "0.25.3"
kotlinx-datetime = "0.4.0"
agp = "8.0.2"
window-size = "0.3.0"
appyx-version = "2.0.0-alpha09"
exposed-version = "0.44.1"
sqlite-jdbc-version = "3.30.1"
markdown-parser-version = "0.5.0"
file-picker-version = "3.0.0"
koin = "3.4.3"
koin-compose = "1.0.4"
kotlinx-io = "0.3.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

window-size = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "window-size" }

appyx-navigation = { module = "com.bumble.appyx:appyx-navigation", version.ref = "appyx-version" }
appyx-interactions = { module = "com.bumble.appyx:appyx-interactions", version.ref = "appyx-version" }
appyx-backstack = { module = "com.bumble.appyx:backstack", version.ref = "appyx-version" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed-version" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed-version" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed-version" }
exposed-money = { module = "org.jetbrains.exposed:exposed-money", version.ref = "exposed-version" }

sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc-version" }

markdown-parser = { module = "org.jetbrains:markdown", version.ref = "markdown-parser-version" }

file-picker = { module = "com.darkrockstudios:mpfilepicker", version.ref = "file-picker-version" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }

kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io"}